### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by oxr463** [nikolajakshic/dagger#15]
See: https://gitlab.com/fdroid/rfp

**Comment by nikolajakshic** [comment]
I'm interested but the process seems pretty involved.

**Comment by oxr463** [comment]
I can submit the request.

**Comment by nikolajakshic** [comment]
That would be great.

**Comment by oxr463** [comment]
See: https://gitlab.com/fdroid/rfp/-/issues/1366

**Comment by nikolajakshic** [comment]
Thanks, I will keep an eye on it.

**Comment by IzzySoft** [comment]
F-Droid maintainer here. Looks pretty good, our bot just confirmed it's fine and builds, thanks! Just one thing: could you establish [Fastlane](https://gitlab.com/snippets/1895688) in your repo here? Just the files, we don't need the binaries. Reasoning behind the link; basically so you can maintain descriptions and screenshots yourself without any hazzle, and all gets picked up automatically with updates. If you want me to cross-check, just ping me when done and before you tag that. Thanks!

**Comment by nikolajakshic** [comment]
@IzzySoft done.

Just to make sure, for future releases, all I need to do is to increment versionCode, versionName, and create a new Tag? Is there anything else that needs to be done from my side?

**Comment by IzzySoft** [comment]
Well, updating some code might help as well :rofl: Honestly: basically that's it. Sometimes the devil is in the details, though (like: keep the tag naming consistent – not switch around with pre- or suffixes; currently it exactly matches the versionName, so that's what will be looked for and all else ignored).

One other pointer: in `full_description.txt`, better use `<ul><li>` for the bullet list. Currently it's no issue, but if the lines go longer they might break on small screens – which with the current bullets would look ugly.

Apart from that: Fastlane looks great, thanks! `build.gradle` is also fine (literal values for versionName/versionCode, great, that enables us to enable auto-updates). Now that just needs to be covered by a tag (so fastlane is detected at our end), and I can push the RFP upstairs to our packagers.

**Comment by nikolajakshic** [comment]
> One other pointer: in `full_description.txt`, better use `<ul><li>` for the bullet list. Currently it's no issue, but if the lines go longer they might break on small screens – which with the current bullets would look ugly.

Suggestion accepted.

> Apart from that: Fastlane looks great, thanks! `build.gradle` is also fine (literal values for versionName/versionCode, great, that enables us to enable auto-updates). Now that just needs to be covered by a tag (so fastlane is detected at our end), and I can push the RFP upstairs to our packagers.

Tagged.

**Comment by IzzySoft** [comment]
Thanks! I've updated the RFP and marked it for our packagers. Hint: Once it's available at F-Droid, please check formatting of the description (F-Droid web & client). You might wish to remove the "blank lines" I intentionally left out from `full_description.txt`, as each line break is replaced by a `<br>` and hence the spaces are now doubled :wink:

**Comment by nikolajakshic** [comment]
Hi @IzzySoft. It's been a while. Do you have any updates?

**Comment by IzzySoft** [comment]
Me? No: my task ends when I add the "ready" label to the RFP – from there on a packager needs to pick up. Uh, that was 3 months ago to the day! Wow… I've pinged our packagers in the hope to rise one of them. Details "over there".

**Comment by IzzySoft** [comment]
Good news: our call has been heard, and a packager confirmed the metadata plus merged them into fdroiddata. If you want to follow the build status, you can find [some helpful links here](https://gitlab.com/snippets/1896503).

**Comment by nikolajakshic** [comment]
https://f-droid.org/en/packages/com.nikola.jakshic.dagger/
